# controllers:
#     resource: ../src/Controller/
#     type: annotation

app_event:
    path: /api/events
    controller: App\Controller\EventController::index
    methods: GET


# kernel:
#     resource: ../src/Kernel.php
#     type: annotation
