controllers:
    resource: ../src/Controller/
    type: annotation

    event_search:
        path: /events
        controller: App\Controller\EventController::index
        methods: GET

kernel:
    resource: ../src/Kernel.php
    type: annotation
